# Generated by Django 2.2.5 on 2019-12-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20191126_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbol',
            name='localizacion',
            field=models.CharField(default='Rancho Quemado', max_length=200),
        ),
    ]
