# Generated by Django 2.2.5 on 2019-12-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_arbol_localizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbol',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
